### ISSUE TITLE
Bad rendering

### ISSUE THREAD

**Issue by stearm** [LyraSearch/docs#4]
Inside the Delete Data [page](https://docs.lyrajs.io/usage/deletion/#delete) there's something wrong in the rendering process:

![Screenshot 2022-08-25 at 10 31 23 AM](https://user-images.githubusercontent.com/14802795/186616796-ff9817cd-babd-4313-9ec2-66943605b355.png)

I locally fixed it by updating the code from:

```
To delete a single document from the database we use the
<a href="/usage/insert-data#doc-ids" >Document ID</a> exposed by the **insert**
method.
```

to:
```
To delete a single document from the database we use the <a href="/usage/insert-data#doc-ids" >Document ID</a> exposed by the **`insert`** method.
```

![Screenshot 2022-08-25 at 10 41 39 AM](https://user-images.githubusercontent.com/14802795/186618216-7acd5678-9d01-432b-a44d-9d2bdc07b051.png)

I believe the new line, along with the "a" tag, is the cause of the behavior. I haven't opened a fix PR because you're most likely using prettier or something similar with a maximum line length set. So maybe it's a global "issue".

## Update - Wrong sections found
- https://docs.lyrajs.io/usage/insert-data#parameters

👋

**Comment by micheleriva** [comment]
Nice spot! would you mind testing this and opening a PR in the case is a prettier problem? 🙏

**Comment by stearm** [comment]
> Nice spot! would you mind testing this and opening a PR in the case is a prettier problem? 🙏

So do you confirm you're using a formatted? In this case, could you please send me the configuration so that I can reproduce it in the proper environment?
